code --install-extension alfnielsen.vsc-organize-imports
code --install-extension anweber.statusbar-commands
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension christian-kohler.path-intellisense
code --install-extension chrmarti.regex
code --install-extension clinyong.vscode-css-modules
code --install-extension cssho.vscode-svgviewer
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension enkia.tokyo-night
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-rename-tag
code --install-extension geddski.macros
code --install-extension GitHub.copilot
code --install-extension Gruntfuggly.activitusbar
code --install-extension ionutvmi.path-autocomplete
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension mhmadhamster.postcss-language
code --install-extension mhutchie.git-graph
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension Orta.vscode-jest
code --install-extension PKief.material-icon-theme
code --install-extension PKief.material-product-icons
code --install-extension redhat.vscode-yaml
code --install-extension richie5um2.vscode-sort-json
code --install-extension ritwickdey.LiveServer
code --install-extension rvest.vs-code-prettier-eslint
code --install-extension shaharkazaz.git-merger
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension TabNine.tabnine-vscode
code --install-extension wmaurer.change-case
